# ================================================
# DZQuantumTeleport Configuration v1.0.0
# Professional Multi-Currency Teleportation Plugin
# ================================================

# ===== RANK SYSTEM =====
rank-system:
  # Detection method: permission (check dzqtp.rank.*), luckperms (use LuckPerms API)
  detection-method: "luckperms"
  
  # Default rank if no rank detected
  default-rank: "default"
  
  # Permission format for rank detection
  permission-format: "dzqtp.rank.{rank}"
  
  # Check rank in real-time or cache
  realtime-check: false
  
  # Cache duration in minutes
  cache-duration: 5
  
  # Rank priority order (highest to lowest)
  priority-order:
    - "admin"
    - "elite"
    - "mvp"
    - "vip"
    - "default"

# ===== LIMIT SYSTEM =====
limit-system:
  # Enable usage limits
  enabled: true
  
  # Reset times (24-hour format)
  reset-times:
    hourly: true  # Reset every hour at minute 0
    daily: "00:00"  # Reset at midnight
    weekly: "MONDAY:00:00"  # Reset on Monday at midnight
    monthly: 1  # Reset on 1st day of month
  
  # Timezone for reset times
  timezone: "UTC"
  
  # Persist limits across restarts
  persistence: true
  
  # Auto-save interval (minutes)
  auto-save-interval: 5
  
  # Notify players when limits reset
  notify-on-reset: true

# ===== COST SYSTEM =====
cost-system:
  # Enable DZEconomy integration
  enabled: true
  
  # Refund costs if teleport cancelled during warmup
  refund-on-cancel: true
  
  # Refund percentage (0.0 - 1.0)
  refund-percentage: 0.75
  
  # Action when insufficient funds: deny, allow-partial, notify
  insufficient-funds-action: "deny"
  
  # Show detailed cost breakdown
  show-breakdown: true
  
  # Charge costs at: start, end
  charge-timing: "start"

# ===== STORAGE =====
storage:
  # Storage type: flatfile, sqlite, mysql
  type: "flatfile"
  
  # FlatFile settings
  flatfile:
    path: "plugins/DZQuantumTeleport/data/"
    auto-save-interval: 300  # seconds
    backup-enabled: true
    backup-count: 3
  
  # SQLite settings
  sqlite:
    file: "plugins/DZQuantumTeleport/data/dzqtp_data.db"
    journal-mode: "WAL"
    cache-size: 10000
    temp-store: "MEMORY"
    auto-vacuum: true
  
  # MySQL settings
  mysql:
    host: "localhost"
    port: 3306
    database: "dzqtp"
    username: "root"
    password: "password"
    table-prefix: "dzqtp_"
    ssl: false
    pool:
      max-connections: 10
      min-idle: 2
      timeout: 30000

# ===== TELEPORTATION =====
teleportation:
  # Warmup system
  warmup:
    enabled: true
    default-delay: 3  # seconds
    
    # Cancel warmup on:
    cancel-on-move: true
    cancel-on-damage: true
    cancel-on-attack: false
    cancel-on-interact: false
    
    # Movement tolerance (blocks)
    movement-tolerance: 0.5
  
  # Safety checks
  safety-checks:
    check-suffocation: true
    check-fall-damage: true
    check-lava: true
    check-fire: true
    check-water-safety: true
    check-cave: true
    check-void: true
    max-fall-distance: 5
  
  # Entity teleportation
  entity-teleportation:
    enabled: true
    max-entities: 10
    types:
      - "HORSE"
      - "DONKEY"
      - "MULE"
      - "LLAMA"
      - "CAT"
      - "WOLF"
      - "PARROT"
  
  # Cross-world teleportation
  cross-world:
    enabled: true
    require-permission: false
    permission: "dzqtp.crossworld"
  
  # Keep inventory on teleport
  keep-inventory: true
  
  # Keep experience on teleport
  keep-experience: true

# ===== RANDOM TELEPORT (RTP) =====
random-teleport:
  # Default world for /rtp
  default-world: "world"
  
  # Global radius (if progressive system disabled)
  min-radius: 100
  max-radius: 5000
  
  # Respect world border
  respect-border: true
  buffer-distance: 10
  
  # Blocked biomes
  blocked-biomes:
    - "OCEAN"
    - "DEEP_OCEAN"
    - "FROZEN_OCEAN"
    - "WARM_OCEAN"
    - "LUKEWARM_OCEAN"
    - "COLD_OCEAN"
    - "DEEP_COLD_OCEAN"
    - "DEEP_LUKEWARM_OCEAN"
    - "DEEP_FROZEN_OCEAN"
    - "MUSHROOM_FIELDS"
  
  # Maximum attempts to find safe location
  max-attempts: 15
  
  # Pre-generate chunks
  pre-generate-chunks: true
  chunk-radius: 2
  
  # Cache safe locations
  cache-enabled: true
  cache-duration: 300  # seconds

# ===== SMART RTP PROGRESSIVE SYSTEM =====
smart-rtp:
  # Enable progressive distance system
  enabled: true
  
  # Distance tiers
  tiers:
    tier-1:
      uses-required: 0
      min-distance: 10
      max-distance: 100
      display-name: "&7Beginner Explorer"
      cost-multiplier: 1.0
    
    tier-2:
      uses-required: 10
      min-distance: 100
      max-distance: 500
      display-name: "&aExplorer"
      cost-multiplier: 1.2
    
    tier-3:
      uses-required: 25
      min-distance: 500
      max-distance: 1000
      display-name: "&bAdventurer"
      cost-multiplier: 1.5
    
    tier-4:
      uses-required: 50
      min-distance: 1000
      max-distance: 2500
      display-name: "&dWanderer"
      cost-multiplier: 2.0
    
    tier-5:
      uses-required: 100
      min-distance: 2500
      max-distance: 5000
      display-name: "&5Voyager"
      cost-multiplier: 2.5
    
    tier-6:
      uses-required: 200
      min-distance: 5000
      max-distance: 10000
      display-name: "&6&lMaster Explorer"
      cost-multiplier: 3.0
  
  # Safety checks
  safety:
    check-suffocation: true
    check-fall-damage: true
    check-lava: true
    check-fire: true
    check-water-depth: true
    max-water-depth: 2
    shore-distance: 10
    check-light-level: true
    min-light-level: 7
    require-sky-access: true
  
  # Safe floor blocks
  safe-blocks:
    - "GRASS_BLOCK"
    - "STONE"
    - "DIRT"
    - "SAND"
    - "GRAVEL"
    - "NETHERRACK"
    - "END_STONE"
    - "SNOW_BLOCK"
    - "ICE"
    - "COARSE_DIRT"
    - "PODZOL"
    - "MYCELIUM"
  
  # Unsafe blocks
  unsafe-blocks:
    - "LAVA"
    - "MAGMA_BLOCK"
    - "FIRE"
    - "SOUL_FIRE"
    - "CACTUS"
    - "SWEET_BERRY_BUSH"
    - "WITHER_ROSE"
  
  # History tracking
  history:
    enabled: true
    max-entries: 100
  
  # Notify on tier upgrade
  notify-tier-upgrade: true

# ===== SPAWN SYSTEM =====
spawn:
  # Use bed spawn if available
  use-bed-spawn: false
  
  # First join spawn (dimension spawn)
  first-join-spawn:
    enabled: true
    world: "world"
  
  # Death spawn
  death-spawn:
    enabled: false
    teleport-to-spawn: false

# ===== BACK SYSTEM =====
back:
  # Save location on teleport
  save-on-teleport: true
  
  # Save location on death
  save-on-death: true
  
  # Maximum history entries per player
  max-history: 5
  
  # Expire after (minutes, -1 = never)
  expire-after: 30

# ===== HOME SYSTEM =====
home:
  # Name validation
  name-validation:
    min-length: 2
    max-length: 16
    allowed-chars: "abcdefghijklmnopqrstuvwxyz0123456789_-"
    case-sensitive: false
  
  # Default icon in GUI
  default-icon: "RED_BED"
  
  # Custom icons per home name
  custom-icons:
    enabled: true
    # Example: home1: "DIAMOND", home2: "EMERALD"

# ===== WARP SYSTEM =====
warp:
  # Public warps visible to all
  public-enabled: true
  
  # Private warps (admin only)
  private-enabled: true
  
  # Warp creation
  creation:
    admin-only: true
    require-permission: false
    permission-format: "dzqtp.warp.create.{name}"
  
  # Name validation
  name-validation:
    min-length: 2
    max-length: 16
    allowed-chars: "abcdefghijklmnopqrstuvwxyz0123456789_-"
    case-sensitive: false
  
  # Quick warp (/<warp_name>)
  quick-warp:
    enabled: true
    priority: 10  # Command priority

# ===== REGION SYSTEM =====
region:
  # Enable region teleport
  enabled: true
  
  # Require WorldEdit for region creation
  worldedit-required: true
  
  # Rank-based region access
  rank-permissions: true
  
  # Region actions
  actions:
    enter: true
    break: true
    place: true
    attack: true
  
  # Default permissions
  default-permissions:
    enter: false
    break: false
    place: false
    attack: false

# ===== TPA SYSTEM =====
tpa:
  # Request settings
  request:
    expire-time: 60  # seconds
    max-pending: 5
    auto-cancel-on-logout: true
  
  # Toggle system
  toggle:
    default-state: true  # Accept requests by default
    persist: true  # Remember toggle state
  
  # Block system
  block:
    enabled: true
    max-blocked: 50

# ===== GUI SYSTEM =====
gui:
  # Enable GUI features
  enabled: true
  
  # GUI sizes (9, 18, 27, 36, 45, 54)
  sizes:
    home: 54
    warp: 54
    tpa-accept: 27
    tpa-deny: 27
    region: 54
  
  # GUI titles
  titles:
    home: "&6&lYour Homes"
    warp: "&b&lAvailable Warps"
    tpa-accept: "&a&lAccept Teleport Request"
    tpa-deny: "&c&lDeny Teleport Request"
    region: "&5&lRegion Management"
  
  # Update interval (ticks)
  update-interval: 20
  
  # Filler items
  filler:
    enabled: true
    material: "GRAY_STAINED_GLASS_PANE"
    name: " "

# ===== SOUNDS =====
sounds:
  # Enable sound effects
  enabled: true
  
  # Sound events
  events:
    teleport-success:
      sound: "ENTITY_ENDERMAN_TELEPORT"
      volume: 1.0
      pitch: 1.0
    
    teleport-cancel:
      sound: "ENTITY_VILLAGER_NO"
      volume: 1.0
      pitch: 1.0
    
    warmup-start:
      sound: "BLOCK_PORTAL_TRIGGER"
      volume: 0.5
      pitch: 1.5
    
    cooldown-active:
      sound: "ENTITY_VILLAGER_NO"
      volume: 0.8
      pitch: 0.8
    
    limit-reached:
      sound: "ENTITY_ITEM_BREAK"
      volume: 1.0
      pitch: 0.5
    
    cost-paid:
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      volume: 1.0
      pitch: 1.2
    
    insufficient-funds:
      sound: "ENTITY_VILLAGER_NO"
      volume: 1.0
      pitch: 0.5
    
    home-set:
      sound: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1.0
      pitch: 2.0
    
    warp-set:
      sound: "BLOCK_ENCHANTMENT_TABLE_USE"
      volume: 1.0
      pitch: 1.0
    
    tpa-request:
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      volume: 0.7
      pitch: 1.5
    
    rtp-tier-upgrade:
      sound: "UI_TOAST_CHALLENGE_COMPLETE"
      volume: 1.0
      pitch: 1.0

# ===== PARTICLES =====
particles:
  # Enable particle effects
  enabled: true
  
  # Built-in effects
  builtin-effects:
    departure:
      type: "PORTAL"
      count: 50
      duration: 20  # ticks
      animation: "spiral"
    
    arrival:
      type: "PORTAL"
      count: 50
      duration: 20
      animation: "explosion"
    
    warmup:
      type: "ENCHANTMENT_TABLE"
      count: 10
      duration: -1  # Continuous during warmup
      animation: "orbit"
    
    home-teleport:
      type: "HEART"
      count: 10
      animation: "spread"
    
    warp-teleport:
      type: "END_ROD"
      count: 30
      animation: "beam"
    
    rtp-teleport:
      type: "ELECTRIC_SPARK"
      count: 40
      animation: "quantum"
    
    failed-teleport:
      type: "SMOKE_LARGE"
      count: 20
      animation: "dissipate"
  
  # PlayerParticles integration
  player-particles:
    enabled: true
    override-builtin: false
  
  # Rank-based particles
  rank-particles:
    default: "PORTAL"
    vip: "SOUL_FIRE_FLAME"
    mvp: "DRAGON_BREATH"
    elite: "END_ROD"
    admin: "FLASH"
  
  # Particle trails during teleport
  trails:
    enabled: true
    duration: 40  # ticks

# ===== LOGGING =====
logging:
  # Console logging
  console:
    enabled: true
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  
  # File logging
  file:
    enabled: true
    path: "plugins/DZQuantumTeleport/logs/"
    rotation: "daily"  # daily, weekly, monthly
    max-files: 30
  
  # Statistics tracking
  statistics:
    enabled: true
    track:
      teleports: true
      costs: true
      cooldowns: true
      limits: true
      rtp-usage: true

# ===== PERFORMANCE =====
performance:
  # Async operations
  async:
    database: true
    teleport-checks: true
    chunk-loading: true
  
  # Cache settings
  cache:
    homes: true
    warps: true
    ranks: true
    cooldowns: true
    limits: true
    duration: 300  # seconds
  
  # Queue system for teleports
  queue:
    enabled: false
    max-size: 100
    process-interval: 1  # ticks

# ===== INTEGRATION =====
integration:
  dzeconomy:
    enabled: true
    required: true
  
  worldedit:
    enabled: true
    required: false
  
  worldguard:
    enabled: true
    required: false
    respect-regions: true
  
  luckperms:
    enabled: true
    required: true
  
  placeholderapi:
    enabled: true
    required: false

# ===== DEVELOPER =====
developer:
  # Debug mode
  debug-mode: false
  
  # Verbose logging
  verbose-logging: false
  
  # Show SQL queries in console
  show-sql-queries: false
  
  # API events
  fire-events: true
