name: DZQuantumTeleport
version: ${version}
main: online.demonzdevelopment.DZQuantumTeleport
api-version: '1.21'
author: hixeda6441
description: Professional multi-currency teleportation plugin with smart RTP
website: https://demonzdevelopment.online

depend:
  - DZEconomy
  - LuckPerms

softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - PlayerParticles

commands:
  tp:
    description: Main teleport command with help menu
    usage: /tp [help|back|accept|deny|spawn|home|<warp>|<player>]
    aliases: [teleport]
  
  dzqtp:
    description: Admin commands for DZQuantumTeleport
    usage: /dzqtp <reload|set|bring|meet|migrate>
    permission: dzqtp.admin
  
  spawn:
    description: Teleport to world spawn
    usage: /spawn [world]
  
  setspawn:
    description: Set spawn point for a world
    usage: /setspawn <world>
    permission: dzqtp.admin.setspawn
  
  sethome:
    description: Create a home at current location
    usage: /sethome <name>
  
  home:
    description: Teleport to a home or manage homes
    usage: /home <name|set|tp|list|delete|remove|rename|move|gui>
  
  listhome:
    description: List all your homes
    usage: /listhome
  
  delhome:
    description: Delete a home
    usage: /delhome <name>
    aliases: [remhome]
  
  renmhome:
    description: Rename a home
    usage: /renmhome <old_name> <new_name>
  
  movhome:
    description: Move a home to your current location
    usage: /movhome <name>
  
  setwarp:
    description: Create a warp
    usage: /setwarp <name> <public|private>
    permission: dzqtp.admin.setwarp
  
  warp:
    description: Teleport to a warp or manage warps
    usage: /warp <name|set|list|delete|remove|rename|visibility|move|gui>
  
  listwarp:
    description: List all accessible warps
    usage: /listwarp
  
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: dzqtp.admin.delwarp
    aliases: [remwarp]
  
  renmwarp:
    description: Rename a warp
    usage: /renmwarp <old_name> <new_name>
    permission: dzqtp.admin.renmwarp
  
  cvwarp:
    description: Change warp visibility
    usage: /cvwarp <name> <public|private>
    permission: dzqtp.admin.cvwarp
  
  movwarp:
    description: Move warp to current location
    usage: /movwarp <name>
    permission: dzqtp.admin.movwarp
  
  rtp:
    description: Random teleport with progressive distance
    usage: /rtp [world]
    aliases: [tpr, randomtp]
  
  tpa:
    description: Request to teleport to a player
    usage: /tpa <player>
  
  call:
    description: Request a player to teleport to you
    usage: /call <player>
  
  bring:
    description: Force teleport a player to you
    usage: /bring <player>
    permission: dzqtp.admin.bring
  
  toggletp:
    description: Toggle receiving teleport requests
    usage: /toggletp <on|off>
  
  rgtp:
    description: Region teleport management
    usage: /rgtp <list|set|rankset|permset|gui>
    aliases: [regiontp, rqtp]

permissions:
  dzqtp.*:
    description: Full access to all features
    default: op
    children:
      dzqtp.admin: true
      dzqtp.command.*: true
      dzqtp.bypass.*: true
  
  dzqtp.admin:
    description: Admin commands access
    default: op
    children:
      dzqtp.admin.setspawn: true
      dzqtp.admin.setwarp: true
      dzqtp.admin.delwarp: true
      dzqtp.admin.renmwarp: true
      dzqtp.admin.cvwarp: true
      dzqtp.admin.movwarp: true
      dzqtp.admin.bring: true
      dzqtp.admin.meet: true
      dzqtp.admin.reload: true
      dzqtp.admin.migrate: true
      dzqtp.admin.regiontp: true
  
  dzqtp.command.*:
    description: All command permissions
    default: true
    children:
      dzqtp.command.tp: true
      dzqtp.command.spawn: true
      dzqtp.command.home: true
      dzqtp.command.warp: true
      dzqtp.command.rtp: true
      dzqtp.command.tpa: true
      dzqtp.command.back: true
  
  dzqtp.bypass.*:
    description: Bypass all restrictions
    default: op
    children:
      dzqtp.bypass.cooldown: true
      dzqtp.bypass.limit: true
      dzqtp.bypass.cost: true
      dzqtp.bypass.warmup: true
      dzqtp.bypass.world: true
  
  dzqtp.rank.default:
    description: Default rank permissions
    default: true
  
  dzqtp.rank.vip:
    description: VIP rank permissions
    default: false
  
  dzqtp.rank.mvp:
    description: MVP rank permissions
    default: false
  
  dzqtp.rank.elite:
    description: Elite rank permissions
    default: false
  
  dzqtp.rank.admin:
    description: Admin rank permissions
    default: op
